version: "3.2"

services:
  webcongdoan_api:
    build:
      context: .
    container_name: web_api
    ports:
      - "5050:80"

  sql:
    image: "toanhhg123/webcongdoan_image_sql:chap1"
    container_name: webcongdoan_sql
    platform: linux/amd64/v3
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=123!@#Aa
